name: jn-galy
channels:
- defaults
- conda-forge
dependencies:
- python=3.10
- pandas=2.2.3
- fastapi=0.112.2
- uvicorn=0.32.1
- gdown=5.2.0
- gensim=4.3.3
- click=8.1.7
- pip
- pip:
  - ruff
  - pytest
